// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB182uFTwPI7-b7zeBTUXh8G2pkG48mZEU',
    appId: '1:592149863108:web:84bdc81771f8668d1b4791',
    messagingSenderId: '592149863108',
    projectId: 'mealmaster-9b774',
    authDomain: 'mealmaster-9b774.firebaseapp.com',
    storageBucket: 'mealmaster-9b774.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAER7wcoE4T6J7ENYweYwJWDiXxJv-_J6A',
    appId: '1:592149863108:android:695e2ce6f5ef797a1b4791',
    messagingSenderId: '592149863108',
    projectId: 'mealmaster-9b774',
    storageBucket: 'mealmaster-9b774.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6Qfp4O7GAVIKJCuJHF2rzCQ2QCKrKSf8',
    appId: '1:592149863108:ios:d7796d8c6924a20f1b4791',
    messagingSenderId: '592149863108',
    projectId: 'mealmaster-9b774',
    storageBucket: 'mealmaster-9b774.appspot.com',
    iosClientId: '592149863108-t0gr71eaaka3607btln5hnba94kstppk.apps.googleusercontent.com',
    iosBundleId: 'com.example.mealmaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6Qfp4O7GAVIKJCuJHF2rzCQ2QCKrKSf8',
    appId: '1:592149863108:ios:d7796d8c6924a20f1b4791',
    messagingSenderId: '592149863108',
    projectId: 'mealmaster-9b774',
    storageBucket: 'mealmaster-9b774.appspot.com',
    iosClientId: '592149863108-t0gr71eaaka3607btln5hnba94kstppk.apps.googleusercontent.com',
    iosBundleId: 'com.example.mealmaster',
  );
}
